name: Publish Docker images
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        llvm: [7, 8, 9, 10, 11, 12, 13, 14]
        ubuntu: [22, 20, 18]
        exclude:
          - ubuntu: 22
            llvm: 7
          - ubuntu: 22
            llvm: 8
          - ubuntu: 22
            llvm: 9
          - ubuntu: 22
            llvm: 10
          - ubuntu: 22
            llvm: 11
          - ubuntu: 22
            llvm: 12
    permissions:
      packages: write
      contents: read
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/ubuntu-${{ matrix.ubuntu }}-llvm-${{ matrix.llvm }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker image (amd64 & arm64)
        if: matrix.ubuntu == 18 || matrix.llvm >= 9
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          build-args: | 
            LLVM_VERSION=${{ matrix.llvm }}
            UBUNTU_VERSION=${{ matrix.ubuntu }}.04
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build and push Docker image (amd64)
        if: matrix.ubuntu != 18 || matrix.llvm < 9
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          build-args: | 
            LLVM_VERSION=${{ matrix.llvm }}
            UBUNTU_VERSION=${{ matrix.ubuntu }}.04
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

